# Generated by Django 4.2.1 on 2023-06-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-modified_at',)},
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='modefied_at',
            new_name='modified_at',
        ),
    ]
